apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-examples
data:
  nodejs-example.js: |
    // Example Redis usage in Node.js
    const Redis = require('ioredis');

    // Connection using environment variables
    const redis = new Redis({
      host: process.env.REDIS_HOST || 'redis-master',
      port: process.env.REDIS_PORT || 6379,
      password: process.env.REDIS_PASSWORD
    });

    // Example cache implementation
    async function getDataWithCache(key) {
      // Try to get from cache
      const cachedData = await redis.get(key);
      if (cachedData) {
        console.log('Cache hit');
        return JSON.parse(cachedData);
      }

      console.log('Cache miss');
      // Fetch from API or database
      const data = await fetchFromApi();

      // Store in cache with TTL (1 hour)
      await redis.set(key, JSON.stringify(data), 'EX', 3600);

      return data;
    }

  python-example.py: |
    # Example Redis usage in Python
    import redis
    import json
    import os

    # Connection using environment variables
    r = redis.Redis(
        host=os.environ.get('REDIS_HOST', 'redis-master'),
        port=os.environ.get('REDIS_PORT', 6379),
        password=os.environ.get('REDIS_PASSWORD', '')
    )

    # Example cache implementation
    def get_data_with_cache(key):
        # Try to get from cache
        cached_data = r.get(key)
        if cached_data:
            print('Cache hit')
            return json.loads(cached_data)

        print('Cache miss')
        # Fetch from API or database
        data = fetch_from_api()

        # Store in cache with TTL (1 hour)
        r.setex(key, 3600, json.dumps(data))

        return data
