apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunpass-deployment
  labels:
    app: bunpass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunpass
  template:
    metadata:
      labels:
        app: bunpass
    spec:
      containers:
      - name: bunpass
        image: daylightx-bunpass:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bunpass-service
spec:
  type: ClusterIP
  selector:
    app: bunpass
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 80800
