apiVersion: apps/v1
kind: Deployment
metadata:
  name: delorean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delorean
  template:
    metadata:
      labels:
        app: delorean
    spec:
      containers:
        - name: delorean
          image: delorean:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
