apiVersion: v1
kind: Service
metadata:
  name: delorean-service
spec:
  selector:
    app: delorean
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
  type: NodePort
